retrospective
01
821
Traceback (most recent call last):
  File "/Users/mikhailnikonorov/Downloads/the-next-episode/chatest2/a3.py", line 254, in <module>
    df_merged.to_csv(f"scraped_files_v3/{keyword}__{year}-{month_i}.csv")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/core/generic.py", line 3721, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/io/formats/format.py", line 1189, in to_csv
    csv_formatter.save()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/io/formats/csvs.py", line 241, in save
    with get_handle(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/io/common.py", line 735, in get_handle
    check_parent_directory(str(handle))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/io/common.py", line 598, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'scraped_files_v3'
retrospective
06
687
06
0
epidemiological
01
1178
01
1726
retrospective
01
821
01
1156
epidemiological
06
884
06
0
retrospective
03
1075
03
1552
epidemiological
03
1704
03
3533
retrospective
08
862
09
816
08
0
09
0
epidemiological
08
1651
09
1664
08
0
09
0
